"""empty message

Revision ID: 0504cebc5441
Revises: 0d6cb1488d95
Create Date: 2022-04-17 00:51:52.722956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0504cebc5441'
down_revision = '0d6cb1488d95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'time')
    # ### end Alembic commands ###
