"""empty message

Revision ID: 103ffd276d4b
Revises: 6afa5d32ec6e
Create Date: 2022-04-06 00:33:31.706944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '103ffd276d4b'
down_revision = '6afa5d32ec6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filament', sa.Column('diameter', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('filament', 'diameter')
    # ### end Alembic commands ###
