"""empty message

Revision ID: 129bc1190be7
Revises: d0f1a0336a94
Create Date: 2022-01-22 01:43:20.053280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '129bc1190be7'
down_revision = 'd0f1a0336a94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filament', sa.Column('diameter', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'filament', 'vendors', ['vendorfk'], ['id'])
    op.create_foreign_key(None, 'filament', 'type', ['typefk'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'filament', type_='foreignkey')
    op.drop_constraint(None, 'filament', type_='foreignkey')
    op.drop_column('filament', 'diameter')
    # ### end Alembic commands ###
