"""empty message

Revision ID: 31584befdbff
Revises: 448594843acd
Create Date: 2022-04-28 22:42:17.823433

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '31584befdbff'
down_revision = '448594843acd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('type', sa.Column('g_per_m_175', sa.Float(), nullable=True))
    op.drop_column('type', 'g_per_m')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('type', sa.Column('g_per_m', mysql.FLOAT(), nullable=True))
    op.drop_column('type', 'g_per_m_175')
    # ### end Alembic commands ###
