"""empty message

Revision ID: 418c4f4ff96d
Revises: 538785dd1eb5
Create Date: 2022-01-20 01:08:52.889763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '418c4f4ff96d'
down_revision = '538785dd1eb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'filament', 'vendors', ['vendorfk'], ['id'])
    op.create_foreign_key(None, 'filament', 'type', ['typefk'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'filament', type_='foreignkey')
    op.drop_constraint(None, 'filament', type_='foreignkey')
    # ### end Alembic commands ###
