"""empty message

Revision ID: 490925f9ce03
Revises: f36db2336d62
Create Date: 2022-05-10 23:52:39.104954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '490925f9ce03'
down_revision = 'f36db2336d62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('postprocessingtime', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'postprocessingtime')
    # ### end Alembic commands ###
