"""empty message

Revision ID: 4b2237d1f590
Revises: e4df905086d1
Create Date: 2022-04-30 23:27:34.251095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b2237d1f590'
down_revision = 'e4df905086d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('gcodefilename', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'gcodefilename')
    # ### end Alembic commands ###
