"""empty message

Revision ID: 4f06daa39ae7
Revises: ad73efe68d44
Create Date: 2022-01-30 23:41:32.124898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f06daa39ae7'
down_revision = 'ad73efe68d44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'filament', 'type', ['typefk'], ['id'])
    op.create_foreign_key(None, 'filament', 'vendors', ['vendorfk'], ['id'])
    op.create_foreign_key(None, 'info_url', 'machine', ['machinefk'], ['id'])
    op.add_column('machine', sa.Column('mach_icon', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('machine', 'mach_icon')
    op.drop_constraint(None, 'info_url', type_='foreignkey')
    op.drop_constraint(None, 'filament', type_='foreignkey')
    op.drop_constraint(None, 'filament', type_='foreignkey')
    # ### end Alembic commands ###
