"""empty message

Revision ID: 538785dd1eb5
Revises: ca5b557d2756
Create Date: 2022-01-20 01:06:03.353175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '538785dd1eb5'
down_revision = 'ca5b557d2756'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'filament', 'type', ['typefk'], ['id'])
    op.create_foreign_key(None, 'filament', 'vendors', ['vendorfk'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'filament', type_='foreignkey')
    op.drop_constraint(None, 'filament', type_='foreignkey')
    # ### end Alembic commands ###
