"""empty message

Revision ID: 5c76b887f3e3
Revises: b6339210de04
Create Date: 2022-04-03 22:21:21.584227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c76b887f3e3'
down_revision = 'b6339210de04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_lineitems', sa.Column('orderfk', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order_lineitems', 'orders', ['orderfk'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_lineitems', type_='foreignkey')
    op.drop_column('order_lineitems', 'orderfk')
    # ### end Alembic commands ###
