"""empty message

Revision ID: 686e2fbfb0e1
Revises: 731af4a8e502
Create Date: 2022-04-20 00:51:16.433772

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '686e2fbfb0e1'
down_revision = '731af4a8e502'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('active_status', sa.Boolean(), nullable=True))
    op.drop_column('orders', 'active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('active', mysql.TINYINT(display_width=1), server_default=sa.text('1'), autoincrement=False, nullable=True))
    op.drop_column('orders', 'active_status')
    # ### end Alembic commands ###
