"""empty message

Revision ID: 69fccf717b85
Revises: 580f54a72a07
Create Date: 2022-04-04 00:45:08.481099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69fccf717b85'
down_revision = '580f54a72a07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('customer_status', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'customer', 'status', ['customer_status'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customer', type_='foreignkey')
    op.drop_column('customer', 'customer_status')
    # ### end Alembic commands ###
