"""empty message

Revision ID: 751641e0748b
Revises: a206570492f2
Create Date: 2022-04-04 21:57:21.670449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '751641e0748b'
down_revision = 'a206570492f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machine', sa.Column('machine_status', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'machine', 'status', ['machine_status'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'machine', type_='foreignkey')
    op.drop_column('machine', 'machine_status')
    # ### end Alembic commands ###
