"""empty message

Revision ID: 8001c519be0d
Revises: c55454ffc4ef
Create Date: 2022-01-17 01:16:53.015800

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8001c519be0d'
down_revision = 'c55454ffc4ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filament', sa.Column('name', sa.String(length=100), nullable=True))
    op.add_column('filament', sa.Column('properties', sa.Text(), nullable=True))
    op.add_column('filament', sa.Column('useage', sa.Text(), nullable=True))
    op.add_column('filament', sa.Column('extruder_temp', sa.JSON(), nullable=True))
    op.add_column('filament', sa.Column('bed_temp', sa.JSON(), nullable=True))
    op.add_column('filament', sa.Column('bed_adhesion', sa.JSON(), nullable=True))
    op.add_column('filament', sa.Column('diameter', sa.JSON(), nullable=True))
    op.create_foreign_key(None, 'filament', 'type', ['typefk'], ['id'])
    op.create_foreign_key(None, 'filament', 'vendors', ['vendorfk'], ['id'])
    op.drop_column('filament', 'filamentname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filament', sa.Column('filamentname', mysql.VARCHAR(length=100), nullable=True))
    op.drop_constraint(None, 'filament', type_='foreignkey')
    op.drop_constraint(None, 'filament', type_='foreignkey')
    op.drop_column('filament', 'diameter')
    op.drop_column('filament', 'bed_adhesion')
    op.drop_column('filament', 'bed_temp')
    op.drop_column('filament', 'extruder_temp')
    op.drop_column('filament', 'useage')
    op.drop_column('filament', 'properties')
    op.drop_column('filament', 'name')
    # ### end Alembic commands ###
