"""empty message

Revision ID: 853c21e5d8d3
Revises: e083322e31eb
Create Date: 2022-01-30 23:42:50.634056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '853c21e5d8d3'
down_revision = 'e083322e31eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'filament', 'type', ['typefk'], ['id'])
    op.create_foreign_key(None, 'filament', 'vendors', ['vendorfk'], ['id'])
    op.create_foreign_key(None, 'info_url', 'machine', ['machinefk'], ['id'])
    op.add_column('machine', sa.Column('picture', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('machine', 'picture')
    op.drop_constraint(None, 'info_url', type_='foreignkey')
    op.drop_constraint(None, 'filament', type_='foreignkey')
    op.drop_constraint(None, 'filament', type_='foreignkey')
    # ### end Alembic commands ###
