"""empty message

Revision ID: 8f005df575b0
Revises: 0a29861d1771
Create Date: 2022-04-28 21:53:06.059667

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8f005df575b0'
down_revision = '0a29861d1771'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filament', sa.Column('initial_length_spool', sa.Integer(), nullable=True))
    op.drop_column('filament', 'length_spool')
    op.alter_column('order_log', 'orderid',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('order_log', 'type',
               existing_type=mysql.ENUM('INSERT', 'UPDATE', 'DELETE'),
               nullable=True)
    op.alter_column('order_log', 'created_by',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('order_log', 'timestamp',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_log', 'timestamp',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('order_log', 'created_by',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('order_log', 'type',
               existing_type=mysql.ENUM('INSERT', 'UPDATE', 'DELETE'),
               nullable=False)
    op.alter_column('order_log', 'orderid',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.add_column('filament', sa.Column('length_spool', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('filament', 'initial_length_spool')
    # ### end Alembic commands ###
