"""empty message

Revision ID: 988f428cd499
Revises: fdfcb6345847
Create Date: 2022-04-05 23:50:18.965149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '988f428cd499'
down_revision = 'fdfcb6345847'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('c_labor', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('c_machine', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('c_materials', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('c_markup', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('shipping', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('c_subtotal', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('c_total', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'c_total')
    op.drop_column('orders', 'c_subtotal')
    op.drop_column('orders', 'shipping')
    op.drop_column('orders', 'c_markup')
    op.drop_column('orders', 'c_materials')
    op.drop_column('orders', 'c_machine')
    op.drop_column('orders', 'c_labor')
    # ### end Alembic commands ###
