"""empty message

Revision ID: 995ee91bf4df
Revises: 853c21e5d8d3
Create Date: 2022-02-01 21:03:30.894497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '995ee91bf4df'
down_revision = '853c21e5d8d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filament', sa.Column('picture', sa.String(length=100), nullable=True))
    op.create_foreign_key(None, 'filament', 'vendors', ['vendorfk'], ['id'])
    op.create_foreign_key(None, 'filament', 'type', ['typefk'], ['id'])
    op.create_foreign_key(None, 'info_url', 'machine', ['machinefk'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'info_url', type_='foreignkey')
    op.drop_constraint(None, 'filament', type_='foreignkey')
    op.drop_constraint(None, 'filament', type_='foreignkey')
    op.drop_column('filament', 'picture')
    # ### end Alembic commands ###
