"""empty message

Revision ID: a08b3156bdab
Revises: 686e2fbfb0e1
Create Date: 2022-04-20 01:46:18.784479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a08b3156bdab'
down_revision = '686e2fbfb0e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_log', sa.Column('orderid', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_log', 'orderid')
    # ### end Alembic commands ###
