"""empty message

Revision ID: a206570492f2
Revises: 69fccf717b85
Create Date: 2022-04-04 01:50:10.590133

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a206570492f2'
down_revision = '69fccf717b85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('project_name', table_name='order_lineitems')
    op.drop_column('order_lineitems', 'date_needed')
    op.drop_column('order_lineitems', 'project_name')
    op.add_column('orders', sa.Column('date_needed', sa.Date(), nullable=True))
    op.add_column('orders', sa.Column('project_name', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'orders', ['project_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='unique')
    op.drop_column('orders', 'project_name')
    op.drop_column('orders', 'date_needed')
    op.add_column('order_lineitems', sa.Column('project_name', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('order_lineitems', sa.Column('date_needed', sa.DATE(), nullable=True))
    op.create_index('project_name', 'order_lineitems', ['project_name'], unique=False)
    # ### end Alembic commands ###
