"""empty message

Revision ID: aa3f5ce9bd9e
Revises: 8001c519be0d
Create Date: 2022-01-17 01:19:24.862444

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aa3f5ce9bd9e'
down_revision = '8001c519be0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'filament', 'vendors', ['vendorfk'], ['id'])
    op.create_foreign_key(None, 'filament', 'type', ['typefk'], ['id'])
    op.drop_column('filament', 'bed_temp')
    op.drop_column('filament', 'bed_adhesion')
    op.drop_column('filament', 'extruder_temp')
    op.drop_column('filament', 'properties')
    op.drop_column('filament', 'useage')
    op.drop_column('filament', 'diameter')
    op.add_column('type', sa.Column('type', sa.String(length=100), nullable=True))
    op.add_column('type', sa.Column('properties', sa.Text(), nullable=True))
    op.add_column('type', sa.Column('useage', sa.Text(), nullable=True))
    op.add_column('type', sa.Column('extruder_temp', sa.JSON(), nullable=True))
    op.add_column('type', sa.Column('bed_temp', sa.JSON(), nullable=True))
    op.add_column('type', sa.Column('bed_adhesion', sa.JSON(), nullable=True))
    op.add_column('type', sa.Column('diameter', sa.JSON(), nullable=True))
    op.drop_column('type', 'typename')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('type', sa.Column('typename', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('type', 'diameter')
    op.drop_column('type', 'bed_adhesion')
    op.drop_column('type', 'bed_temp')
    op.drop_column('type', 'extruder_temp')
    op.drop_column('type', 'useage')
    op.drop_column('type', 'properties')
    op.drop_column('type', 'type')
    op.add_column('filament', sa.Column('diameter', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True))
    op.add_column('filament', sa.Column('useage', mysql.TEXT(), nullable=True))
    op.add_column('filament', sa.Column('properties', mysql.TEXT(), nullable=True))
    op.add_column('filament', sa.Column('extruder_temp', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True))
    op.add_column('filament', sa.Column('bed_adhesion', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True))
    op.add_column('filament', sa.Column('bed_temp', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True))
    op.drop_constraint(None, 'filament', type_='foreignkey')
    op.drop_constraint(None, 'filament', type_='foreignkey')
    # ### end Alembic commands ###
