"""empty message

Revision ID: ab4a96592883
Revises: 74df32eb32fa
Create Date: 2022-03-26 22:40:36.050285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab4a96592883'
down_revision = '74df32eb32fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('userid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'filament', 'type', ['typefk'], ['id'])
    op.create_foreign_key(None, 'filament', 'vendors', ['vendorfk'], ['id'])
    op.create_foreign_key(None, 'info_url', 'machine', ['machinefk'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'info_url', type_='foreignkey')
    op.drop_constraint(None, 'filament', type_='foreignkey')
    op.drop_constraint(None, 'filament', type_='foreignkey')
    op.drop_column('customer', 'userid')
    # ### end Alembic commands ###
