"""empty message

Revision ID: b6339210de04
Revises: 
Create Date: 2022-04-03 03:17:32.266837

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b6339210de04'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_status', sa.Integer(), nullable=True))
    op.drop_constraint('orders_ibfk_3', 'orders', type_='foreignkey')
    op.drop_constraint('orders_ibfk_1', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'status', ['order_status'], ['id'])
    op.drop_column('orders', 'machinefk')
    op.drop_column('orders', 'filamentfk')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('filamentfk', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('machinefk', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_ibfk_1', 'orders', 'machine', ['machinefk'], ['id'])
    op.create_foreign_key('orders_ibfk_3', 'orders', 'filament', ['filamentfk'], ['id'])
    op.drop_column('orders', 'order_status')
    # ### end Alembic commands ###
