"""empty message

Revision ID: ca5b557d2756
Revises: aa3f5ce9bd9e
Create Date: 2022-01-17 01:58:54.324392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca5b557d2756'
down_revision = 'aa3f5ce9bd9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'filament', 'type', ['typefk'], ['id'])
    op.create_foreign_key(None, 'filament', 'vendors', ['vendorfk'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'filament', type_='foreignkey')
    op.drop_constraint(None, 'filament', type_='foreignkey')
    # ### end Alembic commands ###
