"""empty message

Revision ID: d0f1a0336a94
Revises: daded7255c66
Create Date: 2022-01-21 14:42:34.761487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0f1a0336a94'
down_revision = 'daded7255c66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'filament', 'vendors', ['vendorfk'], ['id'])
    op.create_foreign_key(None, 'filament', 'type', ['typefk'], ['id'])
    op.add_column('type', sa.Column('densitygcm3', sa.Float(), nullable=True))
    op.add_column('type', sa.Column('m_in_1kg_3', sa.Float(), nullable=True))
    op.add_column('type', sa.Column('m_in_1kg_175', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('type', 'm_in_1kg_175')
    op.drop_column('type', 'm_in_1kg_3')
    op.drop_column('type', 'densitygcm3')
    op.drop_constraint(None, 'filament', type_='foreignkey')
    op.drop_constraint(None, 'filament', type_='foreignkey')
    # ### end Alembic commands ###
