"""empty message

Revision ID: d3efd0afcd82
Revises: 988f428cd499
Create Date: 2022-04-06 00:24:04.553664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3efd0afcd82'
down_revision = '988f428cd499'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('markuppercent', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'markuppercent')
    # ### end Alembic commands ###
