"""empty message

Revision ID: e083322e31eb
Revises: 4f06daa39ae7
Create Date: 2022-01-30 23:42:30.138910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e083322e31eb'
down_revision = '4f06daa39ae7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'filament', 'vendors', ['vendorfk'], ['id'])
    op.create_foreign_key(None, 'filament', 'type', ['typefk'], ['id'])
    op.create_foreign_key(None, 'info_url', 'machine', ['machinefk'], ['id'])
    op.drop_column('machine', 'picture')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machine', sa.Column('picture', sa.BLOB(), nullable=True))
    op.drop_constraint(None, 'info_url', type_='foreignkey')
    op.drop_constraint(None, 'filament', type_='foreignkey')
    op.drop_constraint(None, 'filament', type_='foreignkey')
    # ### end Alembic commands ###
