"""empty message

Revision ID: e4df905086d1
Revises: 31584befdbff
Create Date: 2022-04-29 00:33:53.187868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4df905086d1'
down_revision = '31584befdbff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('filused', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'filused')
    # ### end Alembic commands ###
