"""empty message

Revision ID: f36db2336d62
Revises: 4b2237d1f590
Create Date: 2022-05-01 00:43:17.648203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f36db2336d62'
down_revision = '4b2237d1f590'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('laborperhour', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'laborperhour')
    # ### end Alembic commands ###
