"""empty message

Revision ID: fbcca40f138b
Revises: 418c4f4ff96d
Create Date: 2022-01-20 23:40:19.845136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbcca40f138b'
down_revision = '418c4f4ff96d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filament', sa.Column('colorhex', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'filament', 'vendors', ['vendorfk'], ['id'])
    op.create_foreign_key(None, 'filament', 'type', ['typefk'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'filament', type_='foreignkey')
    op.drop_constraint(None, 'filament', type_='foreignkey')
    op.drop_column('filament', 'colorhex')
    # ### end Alembic commands ###
